# --------------------------------
# 走査対象外のディレクトリ
# --------------------------------

excluded:
    - scripts
    - Tools

# --------------------------------
# ルールのカスタマイズ
# --------------------------------

# 未参照検出
unused_declaration:
  include_public_and_open: true
